server:
  port: 8085
spring:
  data:
    redis:
      # Redis数据库索引（默认为0）
      database: 2
      # Redis服务器地址
      host: 192.168.200.129
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: 156832zxc@
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.129:3306/yunju-practice?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 156832zxc@
    type: com.zaxxer.hikari.HikariDataSource
logging:
  config: classpath:log4j2-spring.xml
mybatis-flex:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    key-config:
      key-type: generator
      value: snowFlakeId
    logic-delete-column: is_deleted
    print-banner: off